server:
  port: 8101

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.28.132:3306/xueyuan_edu?serverTimezone=GMT%2B8
    username: root
    password: qS43_ew3w234e
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  config: classpath:log4j2-dev.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/lark/eduservice/mapper/xml/*.xml

# 配置阿里云oss的固定值
# 变量名都是自己随便起的
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI4Ftv9Wj7UDAJaFJRJfo2
      keysecret: N5TG2NiClHiihmqVNIuvtjsZvUo209
      bucketname: edudemo111
      host: avatar

eureka: #指定注册中心地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:9002/eureka/
  instance:
    prefer-ip-address: true #eureka服务器上获取的是服务器的ip地址，否则是主机名
