spring:
  application:
    name: pokeball_spider     # 服务名
  profiles:
    active: dev    # 环境设置：dev、prod、test

logging:
  config: classpath:log4j2-dev.xml


biliUrl:
  user:
    onlinePeopleURL: https://api.bilibili.com/x/web-interface/online #当前全网在线人数
    baseUserInfoURL: https://api.bilibili.com/x/space/acc/info?mid= #用户基本信息
    baseRelationURL: http://api.bilibili.com/x/relation/stat?vmid= #粉丝数、关注别人数
    baseUpStatURL: https://api.bilibili.com/x/space/upstat?mid= #播放量、被点赞数
