server:
  port: 8701

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bili_pokeball?serverTimezone=GMT%2B8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 时间格式
    time-zone: GMT+8 # 时区
  redis:
    host: 127.0.0.1 # 使用windows本地的redis，避免延迟
    port: 6379
    database: 1
    password: 123456
    jedis:
      pool:
        ###连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ###连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ###连接池中的最大空闲连接
        max-idle: 5
        ###连接池中的最小空闲连接
        min-idle: 0
      ###连接超时时间
      timeout: 10000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/com/lark/spider/spiderservice/mapper/xml/*.xml

# 配置阿里云oss的固定值
# 变量名都是自己随便起的
aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAI4Ftv9Wj7UDAJaFJRJfo2
      keysecret: N5TG2NiClHiihmqVNIuvtjsZvUo209
      bucketname: edudemo111
      host: avatar

eureka: #指定注册中心地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:9002/eureka/
  instance:
    prefer-ip-address: true #eureka服务器上获取的是服务器的ip地址，否则是主机名
